version: '3'
services:
    ssserver:
        build: .
        volumes:
            - ./ssserver:/ssserver
        command: sh -c "/server.sh"
        environment:
            - HOST_DOMAIN
        ports:
            - "443:443"
