version: '3'
services:
    ssserver:
        image: ssserver
        container_name: ssserver
        restart: always
        build: .
        volumes:
            - ./certs:/etc/certs/
        command: sh -c /server.sh
        environment:
            - HOST_DOMAIN
            - ENCRYPT_METHOD
        ports:
            - 443:443
    ssclient:
        image: ssclient
        container_name: ssclient
        restart: always
        build: .
        volumes:
            - ./certs:/etc/certs/
        command: sh -c /client.sh
        environment:
            - HOST_DOMAIN
            - HOST_PORT
            - ENCRYPT_METHOD
            - PASSWORD
            - LISTEN_PORT
        ports:
            - 5060:1080
